### ISSUE TITLE
BVH How To Get Neighbours Entity For Game Logic

### ISSUE THREAD

**Issue by AtheosCode** [dotsnav/dotsnav#8]

**Comment by AtheosCode** [comment]
`
using DotsNav.BVH;
using DotsNav.Data;
using DotsNav.LocalAvoidance.Data;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;

namespace DotsNav.LocalAvoidance
{
    public static class Utils
    {
        public static NativeList<Entity> ComputeNeighbours(DynamicTreeElementComponent agentTree, float neighbourDist, float2 pos, ComponentDataFromEntity<VelocityObstacleComponent> velocityObstacleLookup)
        {
            var neighbours = new NativeList<Entity>(Allocator.Temp);
            var ext = neighbourDist / 2;
            var aabb = new AABB { LowerBound = pos - ext, UpperBound = pos + ext };
            agentTree.Query(new DistanceCollector(pos, neighbourDist, neighbours, velocityObstacleLookup), aabb);
            return neighbours;
        }
    }

    public struct DistanceCollector : IQueryResultCollector<Entity>
    {
        readonly float2 _position;
        NativeList<Entity> _neighbours;
        readonly ComponentDataFromEntity<VelocityObstacleComponent> _velocityObstacleLookup;
        float _rangeSq;

        public DistanceCollector(float2 position, float range, NativeList<Entity> neighbours, ComponentDataFromEntity<VelocityObstacleComponent> velocityObstacleLookup)
        {
            _position = position;
            _neighbours = neighbours;
            _velocityObstacleLookup = velocityObstacleLookup;
            _rangeSq = Math.Square(range);
        }
        public bool QueryCallback(Entity node)
        {
            var velocityObstacle = _velocityObstacleLookup[node];
            var neighbour = new VelocityObstacle(velocityObstacle);
            var distSq = math.lengthsq(_position - neighbour.Position); 
            if (distSq < _rangeSq)
            {
                _neighbours.Add(node);
            }

            return true;
        }
    }
}`

**Comment by bassmit** [comment]
generally speaking looks fine to me, but you don't need to wrap the velocityObstacleComponent

var neighbour = new VelocityObstacle(velocityObstacle);

I do that to keep track of the distance so I can return the x closest neighbours, where you are returning all neighbours within a given radius.

I would make the collector an internal nested struct to avoid cluttering the namespace, and implement the query as an extension method so it's easier to discover.

public static class DynamicTreeElementComponentExtensions
{
    public static NativeList<Entity> ComputeNeighbours(this DynamicTreeElementComponent agentTree, float neighbourDist,
        float2 pos, ComponentDataFromEntity<VelocityObstacleComponent> velocityObstacleLookup)
    {
        var neighbours = new NativeList<Entity>(Allocator.Temp);
        var ext = neighbourDist / 2;
        var aabb = new AABB {LowerBound = pos - ext, UpperBound = pos + ext};
        agentTree.Query(new DistanceCollector(pos, neighbourDist, neighbours, velocityObstacleLookup), aabb);
        return neighbours;
    }

    struct DistanceCollector : IQueryResultCollector<Entity>
    {
        readonly float2 _position;
        NativeList<Entity> _neighbours;
        readonly ComponentDataFromEntity<VelocityObstacleComponent> _velocityObstacleLookup;
        readonly float _rangeSq;

        public DistanceCollector(float2 position, float range, NativeList<Entity> neighbours,
            ComponentDataFromEntity<VelocityObstacleComponent> velocityObstacleLookup)
        {
            _position = position;
            _neighbours = neighbours;
            _velocityObstacleLookup = velocityObstacleLookup;
            _rangeSq = Math.Square(range);
        }

        public bool QueryCallback(Entity node)
        {
            var velocityObstacle = _velocityObstacleLookup[node];
            var distSq = math.lengthsq(_position - velocityObstacle.Position);
            if (distSq < _rangeSq) 
                _neighbours.Add(node);

            return true;
        }
    }
}

**Comment by bassmit** [comment]
pushed to dev

**Comment by bassmit** [comment]
fyi, to use dev package in a unity project clone dotsnav:dev and add the package using the "from disk" option in your main project (so you have two projects open). Now changes made to the package will trigger reimport in the main project
